apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Demotemplate1
  annotations:
    github.com/project-slug: arnavrazdann/Demotemplate1
spec:
  type: other
  lifecycle: unknown
  owner: innov
